// Your original message, split only to give each thought room on screen.
// Change titles or text here to personalize the presentation.
window.LETTER_SCENES = [
  { seconds: 14, chapter: 'A month of us', title: 'Happy 1st monthsary, darling!', kind: 'opening', text: 'Happy 1st monthsary darling! So okay uhmm pano ko simulan tong speech na to hahaha. Ang dami kong gustong sabihin sayo pero parang kulang pa rin yung words para ma-explain kung gaano ako kasaya at ka-thankful na dumating ka sa buhay ko.' },
  { seconds: 19, chapter: 'A month of us', title: 'One month. So many memories.', kind: 'letter', text: 'Darling, thankyou kase dumating ka sa buhay ko at napasaya moko, d ko inexpect na 1month na tayo since we became official, tangina feel ko parang 10 years na tayo in relationship eh HAHA sa dami ba namang rough days, tampuhan, misunderstandings, at kung ano anong pinagdaanan natin in just one month.' },
  { seconds: 18, chapter: 'A month of us', title: 'We keep choosing each other.', kind: 'letter', text: 'Even though we’ve been through a lot of ups and downs, we still choose to work through our problems and stay together. Kase hindi talaga pepwede na puro tayo ma pride sa isat isa kaya hanggat kaya ko dinadown ko talaga pride ko kase mahal na mahal kita at ayoko mag settle for less,' },
  { seconds: 9, chapter: 'A month of us', title: 'Bakit hindi habang buhay?', kind: 'statement', text: 'gusto ko matagalang relationship talaga kung pepwede nga lang habang buhay bakit hindi?' },
  { seconds: 14, chapter: 'It started with Roblox', title: 'Just one game. Then you.', kind: 'letter', text: 'Nakakatawa rin isipin kung pano tayo naging close, sa roblox nag simula ang lahat HAHAHA habang naglalaro tayo, unti unti na rin pala kitang nakikilala at nagiging importante ka na saken.' },
  { seconds: 16, chapter: 'It started with Roblox', title: 'From Roblox, to us.', kind: 'roblox', text: 'From Roblox, tawanan, kulitan, hanggang sa naging tayo. Sino ba namang mag aakala na sa simpleng laro makikita ko yung taong gusto kong makalaro hindi lang sa Roblox, kundi makasama rin sa laro ng buhay.' },
  { seconds: 21, chapter: 'It started with Roblox', title: 'I’m so glad I found you.', photo: 'scene-memory-4', text: 'Darling! thankyou kasi hindi talaga ako nag kakamali na ichchase kita kase at first sabi ko "parang mabait naman ata tong babaeng to hindi party goers, family oriented". Habang mas nakikilala kita, mas lalo kong naa-appreciate kung sino ka. Ang saya lang isipin na yung babaeng gusto ko lang makilala noon, ngayon tinatawag ko nang darling. ♡' },
  { seconds: 16, chapter: 'The little things', title: 'You probably don’t even notice.', photo: 'scene-memory-5', text: 'Darling much appreciated ko talaga yung mga maliit na bagay na ginagawa mo, even the things you probably don’t notice yourself like yung inaantay moko pagkaout ko taena para saken malaking bagay na yun' },
  { seconds: 15, chapter: 'The little things', title: '11:00 PM.', kind: 'clock', text: 'tas tanda ko pa yung sabi mo nung nag live ka na mag eend ka ng 11pm (off duty time ko yan) taena sobrang happy ko that time na yan taena tuwang tuwa talaga ako para akong bata sa sobrang saya HAHAHA' },
  { seconds: 10, chapter: 'The little things', title: 'That kind of happy.', photo: 'scene-memory-1', text: 'yung tipong d nako nakain ng dinner sa sobrang excited na para bang busog na HAHAHA.' },
  { seconds: 18, chapter: 'The future I see', title: 'You make me want to be better.', kind: 'video', text: 'You deserve all the best darling, hindi ko kaya mawala ka not because your beautiful, sexy, or attractive but because you inspired me, motivates me, na para bang gusto ko pang ipush yung sarili ko to be a successful/better person,' },
  { seconds: 9, chapter: 'The future I see', title: 'You’re part of my tomorrow.', kind: 'statement', text: 'kasi kung mawala ka siguro sapat na ako sa kung anong meron ako now.' },
  { seconds: 14, chapter: 'The future I see', title: 'A life with you in it.', kind: 'memories', text: 'Gusto ko mabigay sayo yung buhay na deserve mo, gusto ko darating yung araw na masabi ko na lahat ng pagod, sacrifices at pagpupursige ko is worth it kasi kasama kita.' },
  { seconds: 11, chapter: 'The future I see', title: 'We’re only just beginning.', kind: 'letter', text: 'Darling! I know na one month palang tayo, marami pa tayong pagdadaanan, marami pa tayong matututunan about each other, at siguradong may tampuhan at away pa sa future XD.' },
  { seconds: 10, chapter: 'The future I see', title: 'Remember why we started.', kind: 'letter', text: 'Pero sana kahit ano mangyari, wag nating kalimutan kung bakit tayo nagsimula at bakit natin pinili ang isa’t isa.' },
  { seconds: 13, chapter: 'Still choosing you', title: 'Day and night.', kind: 'poem', text: 'From Roblox nights to holding each other tight,\nFrom simple talks to making things right.\nThrough every problem, every fight,\nI’ll still choose you, day and night. ❤️' },
  { seconds: 12, chapter: 'Still choosing you', title: 'My happiness. My inspiration.', kind: 'duo', text: 'Happy 1st monthsary, darling.\n\nThank you for being my happiness, my inspiration, and one of the reasons why I want to become better every day.' },
  { seconds: 8, chapter: 'Still choosing you', title: 'A lifetime to go.', kind: 'finale', text: 'I love you so much. One month down, and hopefully a lifetime to go. ❤️' }
];
